const FREE_EXERCISE_DB_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";
const OPENFIT_BASE = "https://raw.githubusercontent.com/gsuiffet/openfit/master/exercises";
const WIKIMEDIA_COMMONS_BASE = "https://upload.wikimedia.org/wikipedia/commons";

function freeExercisePair(id: string): [string, string] {
  return [`${FREE_EXERCISE_DB_BASE}/${id}/0.jpg`, `${FREE_EXERCISE_DB_BASE}/${id}/1.jpg`];
}

function openfitPair(id: string): [string, string] {
  return [`${OPENFIT_BASE}/${id}/images/0.webp`, `${OPENFIT_BASE}/${id}/images/1.webp`];
}

function wikimediaPair(startPath: string, endPath: string): [string, string] {
  return [`${WIKIMEDIA_COMMONS_BASE}/${startPath}`, `${WIKIMEDIA_COMMONS_BASE}/${endPath}`];
}

export const exerciseImageMap: Record<string, [string, string]> = {
  "barbell-bench-press": freeExercisePair("Barbell_Bench_Press_-_Medium_Grip"),
  "dumbbell-bench-press": freeExercisePair("Dumbbell_Bench_Press"),
  "incline-dumbbell-press": freeExercisePair("Incline_Dumbbell_Press"),
  "decline-bench-press": freeExercisePair("Decline_Barbell_Bench_Press"),
  "machine-chest-press": freeExercisePair("Leverage_Chest_Press"),
  "smith-machine-bench-press": freeExercisePair("Smith_Machine_Bench_Press"),
  "dumbbell-fly": freeExercisePair("Dumbbell_Flyes"),
  "incline-dumbbell-fly": freeExercisePair("Incline_Dumbbell_Flyes"),
  "cable-crossover": freeExercisePair("Cable_Crossover"),
  "low-cable-fly": freeExercisePair("Low_Cable_Crossover"),
  "push-up": freeExercisePair("Pushups"),
  "incline-push-up": freeExercisePair("Incline_Push-Up"),
  "deficit-push-up": freeExercisePair("Decline_Push-Up"),
  "chest-dip": freeExercisePair("Dips_-_Chest_Version"),
  "wide-grip-lat-pulldown": freeExercisePair("Wide-Grip_Lat_Pulldown"),
  "close-grip-pulldown": freeExercisePair("Close-Grip_Front_Lat_Pulldown"),
  "straight-arm-pulldown": freeExercisePair("Straight-Arm_Pulldown"),
  "barbell-row": freeExercisePair("Bent_Over_Barbell_Row"),
  "seated-cable-row": freeExercisePair("Seated_Cable_Rows"),
  "single-arm-dumbbell-row": freeExercisePair("One-Arm_Dumbbell_Row"),
  "chest-supported-row": freeExercisePair("Dumbbell_Incline_Row"),
  "assisted-pull-up": freeExercisePair("Band_Assisted_Pull-Up"),
  "pull-up": freeExercisePair("Pullups"),
  "chin-up": freeExercisePair("Chin-Up"),
  "inverted-row": freeExercisePair("Inverted_Row"),
  "standing-overhead-press": freeExercisePair("Standing_Military_Press"),
  "seated-dumbbell-press": freeExercisePair("Seated_Dumbbell_Press"),
  "arnold-press": freeExercisePair("Arnold_Dumbbell_Press"),
  "landmine-press": freeExercisePair("Landmine_Linear_Jammer"),
  "machine-shoulder-press": freeExercisePair("Machine_Shoulder_Military_Press"),
  "dumbbell-lateral-raise": freeExercisePair("Side_Lateral_Raise"),
  "cable-lateral-raise": freeExercisePair("Cable_Seated_Lateral_Raise"),
  "bent-over-rear-delt-raise": freeExercisePair("Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench"),
  "front-raise": freeExercisePair("Front_Dumbbell_Raise"),
  "face-pull": freeExercisePair("Face_Pull"),
  "upright-row": freeExercisePair("Upright_Barbell_Row"),
  "y-raise": freeExercisePair("One-Arm_Incline_Lateral_Raise"),
  "reverse-pec-deck": freeExercisePair("Cable_Rear_Delt_Fly"),
  "barbell-curl": freeExercisePair("Barbell_Curl"),
  "ez-bar-curl": freeExercisePair("EZ-Bar_Curl"),
  "alternating-dumbbell-curl": freeExercisePair("Dumbbell_Alternate_Bicep_Curl"),
  "hammer-curl": freeExercisePair("Hammer_Curls"),
  "preacher-curl": freeExercisePair("Preacher_Curl"),
  "cable-curl": freeExercisePair("Standing_Biceps_Cable_Curl"),
  "cable-triceps-pressdown": freeExercisePair("Triceps_Pushdown"),
  "overhead-rope-extension": freeExercisePair("Triceps_Overhead_Extension_with_Rope"),
  "skull-crusher": freeExercisePair("EZ-Bar_Skullcrusher"),
  "close-grip-bench-press": freeExercisePair("Close-Grip_Barbell_Bench_Press"),
  "dumbbell-kickback": freeExercisePair("Tricep_Dumbbell_Kickback"),
  "bench-dip": freeExercisePair("Bench_Dips"),
  "single-arm-cable-extension": freeExercisePair("Cable_One_Arm_Tricep_Extension"),
  "back-squat": freeExercisePair("Barbell_Squat"),
  "front-squat": freeExercisePair("Front_Barbell_Squat"),
  "goblet-squat": freeExercisePair("Goblet_Squat"),
  "hack-squat": freeExercisePair("Hack_Squat"),
  "leg-press": freeExercisePair("Leg_Press"),
  "bulgarian-split-squat": freeExercisePair("Split_Squat_with_Dumbbells"),
  "romanian-deadlift": freeExercisePair("Romanian_Deadlift"),
  "trap-bar-deadlift": freeExercisePair("Trap_Bar_Deadlift"),
  "stiff-leg-deadlift": freeExercisePair("Stiff-Legged_Barbell_Deadlift"),
  "good-morning": freeExercisePair("Good_Morning"),
  "hip-thrust": freeExercisePair("Barbell_Hip_Thrust"),
  "glute-bridge": freeExercisePair("Barbell_Glute_Bridge"),
  "walking-lunge": freeExercisePair("Barbell_Walking_Lunge"),
  "reverse-lunge": freeExercisePair("Dumbbell_Rear_Lunge"),
  "step-up": freeExercisePair("Barbell_Step_Ups"),
  crunch: freeExercisePair("Crunches"),
  "reverse-crunch": freeExercisePair("Reverse_Crunch"),
  "v-up": freeExercisePair("Sit-Up"),
  "heel-tap-crunch": freeExercisePair("Cross-Body_Crunch"),
  "dead-bug": freeExercisePair("Dead_Bug"),
  "mountain-climber": freeExercisePair("Mountain_Climbers"),
  "incline-walk": freeExercisePair("Walking_Treadmill"),
  "treadmill-run": freeExercisePair("Running_Treadmill"),
  "air-bike-sprint": freeExercisePair("Air_Bike"),
  "rowing-sprint": freeExercisePair("Rowing_Stationary"),
  "jump-rope": freeExercisePair("Rope_Jumping"),
  "battle-rope-waves": freeExercisePair("Battling_Ropes"),
  "shuttle-run": freeExercisePair("Single-Cone_Sprint_Drill"),
  "stair-climber-push": freeExercisePair("Stairmaster"),
  "cycling-sprint": freeExercisePair("Bicycling_Stationary"),
  "bear-crawl-hold": freeExercisePair("Spider_Crawl"),
  "hanging-knee-raise": freeExercisePair("Hanging_Leg_Raise"),
  "box-jump": freeExercisePair("Box_Jump_Multiple_Response"),
  "jump-squat": freeExercisePair("Freehand_Jump_Squat"),
  burpee: wikimediaPair("c/c5/Burpee_2_Squat.jpg", "f/f5/Burpee_5_Thrust.jpg"),
  "kettlebell-swing": freeExercisePair("One-Arm_Kettlebell_Swings"),
  "sled-push": freeExercisePair("Sled_Push"),
  "sled-pull": freeExercisePair("Sled_Drag_-_Harness"),
  "farmer-carry-march": freeExercisePair("Farmers_Walk"),
  "shadow-boxing-intervals": freeExercisePair("Heavy_Bag_Thrust"),
  "broad-jump": freeExercisePair("Standing_Long_Jump"),
  "skater-hop": freeExercisePair("Single-Leg_Lateral_Hop"),
  "split-jump": freeExercisePair("Split_Jump"),
  "lateral-bound": freeExercisePair("Lateral_Bound"),
  "depth-jump": freeExercisePair("Depth_Jump_Leap"),
  "tuck-jump": freeExercisePair("Knee_Tuck_Jump"),
  "pogo-hop": freeExercisePair("Single-Leg_Hop_Progression"),
  "medicine-ball-slam": freeExercisePair("One-Arm_Medicine_Ball_Slam"),
  "russian-twist": freeExercisePair("Russian_Twist"),
  "rotational-med-ball-throw": freeExercisePair("Medicine_Ball_Full_Twist"),
};

export function getExerciseImageUrls(exerciseId: string): [string, string] | null {
  return exerciseImageMap[exerciseId] ?? null;
}
