export const exerciseImageMap: Record<string, string> = {
  "barbell-bench-press": "Barbell_Bench_Press_-_Medium_Grip",
  "incline-dumbbell-press": "Incline_Dumbbell_Press",
  "decline-bench-press": "Decline_Barbell_Bench_Press",
  "machine-chest-press": "Leverage_Chest_Press",
  "smith-machine-bench-press": "Smith_Machine_Bench_Press",
  "dumbbell-fly": "Dumbbell_Flyes",
  "incline-dumbbell-fly": "Incline_Dumbbell_Flyes",
  "cable-crossover": "Cable_Crossover",
  "push-up": "Pushups",
  "incline-push-up": "Incline_Push-Up",
  "chest-dip": "Dips_-_Chest_Version",
  "wide-grip-lat-pulldown": "Wide-Grip_Lat_Pulldown",
  "close-grip-pulldown": "Close-Grip_Front_Lat_Pulldown",
  "straight-arm-pulldown": "Straight-Arm_Pulldown",
  "barbell-row": "Bent_Over_Barbell_Row",
  "seated-cable-row": "Seated_Cable_Rows",
  "single-arm-dumbbell-row": "One-Arm_Dumbbell_Row",
  "pull-up": "Pullups",
  "chin-up": "Chin-Up",
  "inverted-row": "Inverted_Row",
  "standing-overhead-press": "Standing_Military_Press",
  "seated-dumbbell-press": "Seated_Dumbbell_Press",
  "arnold-press": "Arnold_Dumbbell_Press",
  "machine-shoulder-press": "Machine_Shoulder_Military_Press",
  "dumbbell-lateral-raise": "Side_Lateral_Raise",
  "front-raise": "Front_Dumbbell_Raise",
  "face-pull": "Face_Pull",
  "upright-row": "Upright_Barbell_Row",
  "barbell-curl": "Barbell_Curl",
  "ez-bar-curl": "EZ-Bar_Curl",
  "alternating-dumbbell-curl": "Dumbbell_Alternate_Bicep_Curl",
  "hammer-curl": "Hammer_Curls",
  "preacher-curl": "Preacher_Curl",
  "cable-curl": "Standing_Biceps_Cable_Curl",
  "cable-triceps-pressdown": "Triceps_Pushdown",
  "overhead-rope-extension": "Triceps_Overhead_Extension_with_Rope",
  "skull-crusher": "EZ-Bar_Skullcrusher",
  "close-grip-bench-press": "Close-Grip_Barbell_Bench_Press",
  "dumbbell-kickback": "Tricep_Dumbbell_Kickback",
  "bench-dip": "Bench_Dips",
  "back-squat": "Barbell_Squat",
  "front-squat": "Front_Barbell_Squat",
  "goblet-squat": "Goblet_Squat",
  "hack-squat": "Hack_Squat",
  "leg-press": "Leg_Press",
  "bulgarian-split-squat": "Split_Squat_with_Dumbbells",
  "romanian-deadlift": "Romanian_Deadlift",
  "trap-bar-deadlift": "Trap_Bar_Deadlift",
  "stiff-leg-deadlift": "Stiff-Legged_Barbell_Deadlift",
  "good-morning": "Good_Morning",
  "hip-thrust": "Barbell_Hip_Thrust",
  "glute-bridge": "Barbell_Glute_Bridge",
  "walking-lunge": "Barbell_Walking_Lunge",
  "reverse-lunge": "Dumbbell_Rear_Lunge",
  "step-up": "Barbell_Step_Ups",
  crunch: "Crunches",
  "reverse-crunch": "Reverse_Crunch",
  "russian-twist": "Russian_Twist",
  "dead-bug": "Dead_Bug",
  "mountain-climber": "Mountain_Climbers",
  "front-plank": "Plank",
  "box-jump": "Box_Jump_Multiple_Response",
  "jump-squat": "Freehand_Jump_Squat",
  burpee: "Burpee",
  "kettlebell-swing": "One-Arm_Kettlebell_Swings",
  "sled-push": "Sled_Push",
  "farmer-carry-march": "Farmers_Walk",
};

const IMAGE_BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export function getExerciseImageUrls(exerciseId: string): [string, string] | null {
  const dbId = exerciseImageMap[exerciseId];
  if (!dbId) return null;

  return [`${IMAGE_BASE}/${dbId}/0.jpg`, `${IMAGE_BASE}/${dbId}/1.jpg`];
}
